const httpStatus = {
    HTTP_SUCCESS:200,
    HTTP_CREATED:201,
    HTTP_BAD_REQUEST:400,
    HTTP_NOT_FOUND:404,
    HTTP_INTERNAL_SERVER_ERROR:500,
    HTTP_FORBIDDEN:403,
    HTTP_UNAUTHORIZED: 401
}

module.exports = httpStatus;